spring:
  application:
    name: sub-table
  profiles:
    active: dev
server:
  port: 8080
management:
  server:
    port: 8081
  endpoint:
    health:
      show-details: always
  endpoints:
    jmx:
      exposure:
        include: '*'
    web:
      exposure:
        include: '*'